#define WS_PROJETO_BPE               "bpe"
#define WS_PROJETO_CTE               "cte"
#define WS_PROJETO_MDFE              "mdfe"
#define WS_PROJETO_NFE               "nfe"

#define WS_AMBIENTE_HOMOLOGACAO      "2"
#define WS_AMBIENTE_PRODUCAO         "1"

#define WS_XMLNS_BPE                 [xmlns="http://www.portalfiscal.inf.br/bpe"]
#define WS_XMLNS_CTE                 [xmlns="http://www.portalfiscal.inf.br/cte"]
#define WS_XMLNS_NFE                 [xmlns="http://www.portalfiscal.inf.br/nfe"]
#define WS_XMLNS_MDFE                [xmlns="http://www.portalfiscal.inf.br/mdfe"]

#define WS_RETORNA_PROTOCOLO    "1"
#define WS_RETORNA_RECIBO       "0"

#define XML_UTF8                   [<?xml version="1.0" encoding="UTF-8"?>]

#define WS_BPE_CONSULTAPROTOCOLO { ;
         { "MS",   "1.00P", "https://bpe.fazenda.ms.gov.br/ws/BPeConsulta" }, ;
         { "SVRS", "1.00P", "https://bpe.svrs.rs.gov.br/ms/bpeConsulta.asmx" }, ;
         ;
         { "MS",   "1.00H", "https://homologacao.bpe.ms.gov.br/ws/BPeConsulta" } }

#define WS_BPE_STATUSSERVICO { ;
         { "MS",   "1.00P", "https://bpe.fazenda.ms.gov.br/ws/BPeStatusServico" }, ;
         { "SVRS", "1.00P", "https://bpe.svrs.rs.gov.br/ms/bpeStatusServico/bpeStatusServico.asmx" }, ;
         ;
         { "MS",   "1.00H", "https://homologacao.bpe.ms.gov.br/ws/BPeStatusServico" }, ;
         { "SVRS", "1.00H", "https://bpe-homologacao.svrs.rs.gov.br/ws/bpeStatusServico/bpeStatusServico.asmx" } }

#define WS_CTE_CONSULTAPROTOCOLO { ;
         { "MG",   "3.00P", "https://cte.fazenda.mg.gov.br/cte/services/CteConsulta" }, ;
         { "MS",   "3.00P", "https://producao.cte.ms.gov.br/ws/CteConsulta" }, ;
         { "MT",   "3.00P", "https://cte.sefaz.mt.gov.br/ctews/services/CteConsulta" }, ;
         { "SP",   "3.00P", "https://nfe.fazenda.sp.gov.br/cteWEB/services/cteConsulta.asmx" }, ;
         { "PR",   "3.00P", "https://cte.fazenda.pr.gov.br/cte/CteConsulta?wsdl" }, ;
         { "SVSP", "3.00P", "https://nfe.fazenda.sp.gov.br/cteWEB/services/CteConsulta.asmx" }, ;
         { "SVRS", "3.00P", "https://cte.svrs.rs.gov.br/ws/cteconsulta/CteConsulta.asmx" }, ;
         ;
         { "SP",   "3.00H", "https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteConsulta.asmx" }, ;
         { "SVRS", "3.00H", "https://cte-homologacao.svrs.rs.gov.br/ws/cteconsulta/CteConsulta.asmx" } }

#define WS_CTE_CONSULTARECIBO { ;
      { "MG",   "3.00P", "https://cte.fazenda.mg.gov.br/cte/services/CteRetRecepcao" }, ;
      { "MS",   "3.00P", "https://producao.cte.ms.gov.br/ws/CteRetRecepcao" }, ;
      { "MT",   "3.00P", "https://cte.sefaz.mt.gov.br/ctews/services/CteRetRecepcao" }, ;
      { "PR",   "3.00P", "https://cte.fazenda.pr.gov.br/cte/CteRetRecepcao?wsdl" }, ;
      { "SP",   "3.00P", "https://nfe.fazenda.sp.gov.br/cteWEB/services/cteRetRecepcao.asmx" }, ;
      { "SVSP", "3.00P", "https://nfe.fazenda.sp.gov.br/cteWEB/services/CteRetRecepcao.asmx" }, ;
      { "SVRS", "3.00P", "https://cte.svrs.rs.gov.br/ws/cteretrecepcao/cteRetRecepcao.asmx" }, ;
      ;
      { "SP",   "3.00H", "https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteRetRecepcao.asmx" }, ;
      { "SVRS", "3.00H", "https://cte-homologacao.svrs.rs.gov.br/ws/cteretrecepcao/cteRetRecepcao.asmx" } }

#define WS_CTE_ENVIAEVENTO { ;
      { "MG",   "3.00P", "https://cte.fazenda.mg.gov.br/cte/services/RecepcaoEvento" }, ;
      { "MS",   "3.00P", "https://producao.cte.ms.gov.br/ws/CteRecepcaoEvento" }, ;
      { "MT",   "3.00P", "https://cte.sefaz.mt.gov.br/ctews2/services/CteRecepcaoEvento?wsdl" }, ;
      { "PR",   "3.00P", "https://cte.fazenda.pr.gov.br/cte/CteRecepcaoEvento?wsdl" }, ;
      { "SP",   "3.00P", "https://nfe.fazenda.sp.gov.br/cteweb/services/cteRecepcaoEvento.asmx" }, ;
      { "SVRS", "3.00P", "https://cte.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx" }, ;
      ;
      { "SP",   "3.00H", "https://homologacao.nfe.fazenda.sp.gov.br/cteweb/services/cteRecepcaoEvento.asmx" }, ;
      { "SVRS", "3.00H", "https://cte-homologacao.svrs.rs.gov.br/ws/cterecepcaoevento/cterecepcaoevento.asmx" } }

#define WS_CTE_INUTILIZA { ;
      { "MG",   "3.00P", "https://cte.fazenda.mg.gov.br/cte/services/CteInutilizacao" }, ;
      { "MS",   "3.00P", "https://producao.cte.ms.gov.br/ws/CteInutilizacao" }, ;
      { "MT",   "3.00P", "https://cte.sefaz.mt.gov.br/ctews/services/CteInutilizacao" }, ;
      { "PR",   "3.00P", "https://cte.fazenda.pr.gov.br/cte/CteInutilizacao?wsdl" }, ;
      { "SP",   "3.00P", "https://nfe.fazenda.sp.gov.br/cteWEB/services/cteInutilizacao.asmx" }, ;
      { "SVRS", "3.00P", "https://cte.svrs.rs.gov.br/ws/cteinutilizacao/cteinutilizacao.asmx" }, ;
      ;
      { "SP",   "3.00H", "https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteInutilizacao.asmx" }, ;
      { "SVRS", "3.00H", "https://cte-homologacao.svrs.rs.gov.br/ws/cteinutilizacao/cteinutilizacao.asmx" } }

#define WS_CTE_ENVIALOTE { ;
      { "MG",   "3.00P", "https://cte.fazenda.mg.gov.br/cte/services/CteRecepcao" }, ;
      { "MS",   "3.00P", "https://producao.cte.ms.gov.br/ws/CteRecepcao" }, ;
      { "MT",   "3.00P", "https://cte.sefaz.mt.gov.br/ctews/services/CteRecepcao" }, ;
      { "PR",   "3.00P", "https://cte.fazenda.pr.gov.br/cte/CteRecepcao?wsdl" }, ;
      { "SP",   "3.00P", "https://nfe.fazenda.sp.gov.br/cteWEB/services/cteRecepcao.asmx" }, ;
      { "SVSP", "3.00P", "https://nfe.fazenda.sp.gov.br/cteWEB/services/cteRecepcao.asmx" }, ;
      { "SVRS", "3.00P", "https://cte.svrs.rs.gov.br/ws/cterecepcao/CteRecepcao.asmx" }, ;
      ;
      { "SP",   "3.00H", "https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteRecepcao.asmx" }, ;
      { "SVRS", "3.00H", "https://cte-homologacao.svrs.rs.gov.br/ws/cterecepcao/CteRecepcao.asmx" } }

#define WS_CTE_STATUSSERVICO { ;
      { "MG",   "3.00P", "https://cte.fazenda.mg.gov.br/cte/services/CteStatusServico" }, ;
      { "MT",   "3.00P", "https://cte.sefaz.mt.gov.br/ctews/services/CteStatusServico" }, ;
      { "MS",   "3.00P", "https://producao.cte.ms.gov.br/ws/CteStatusServico" }, ;
      { "PR",   "3.00P", "https://cte.fazenda.pr.gov.br/cte/CteStatusServico?wsdl" }, ;
      { "SP",   "3.00P", "https://nfe.fazenda.sp.gov.br/cteWEB/services/cteStatusServico.asmx" }, ;
      { "SVSP", "3.00P", "https://nfe.fazenda.sp.gov.br/cteWEB/services/CteStatusServico.asmx" }, ;
      { "SVRS", "3.00P", "https://cte.svrs.rs.gov.br/ws/ctestatusservico/CteStatusServico.asmx" }, ;
      ;
      { "SP",   "3.00H", "https://homologacao.nfe.fazenda.sp.gov.br/cteWEB/services/cteStatusServico.asmx" }, ;
      { "SVRS", "3.00H", "https://cte-homologacao.svrs.rs.gov.br/ws/ctestatusservico/CteStatusServico.asmx" } }

#define WS_MDFE_CONSULTANAOENCERRADOS { ;
         { "**", "3.00P", "https://mdfe.svrs.rs.gov.br/ws/mdfeConsNaoEnc/mdfeConsNaoenc.asmx" }, ;
         { "**", "3.00H", "https://mdfe-homologacao.svrs.rs.gov.br/ws/MDFeConsNaoEnc/MDFeConsNaoEnc.asmx" } }

#define WS_MDFE_CONSULTAPROTOCOLO { ;
      { "**", "3.00P", "https://mdfe.svrs.rs.gov.br/ws/MDFeConsulta/MDFeConsulta.asmx" }, ;
      { "**", "3.00H", "https://mdfe-homologacao.svrs.rs.gov.br/ws/MDFeConsulta/MDFeConsulta.asmx" } }

#define WS_MDFE_CONSULTARECIBO { ;
      { "**", "3.00P", "https://mdfe.svrs.rs.gov.br/ws/MDFeRetRecepcao/MDFeRetRecepcao.asmx" }, ;
      { "**", "3.00H", "https://mdfe-homologacao.svrs.rs.gov.br/ws/MDFeRetRecepcao/MDFeRetRecepcao.asmx" } }

#define WS_MDFE_DISTRIBUICAO { ;
      { "**", "3.00P", "https://mdfe.svrs.rs.gov.br/WS/MDFeDistribuicaoDFe/MDFeDistribuicaoDFe.asmx" } }

#define WS_MDFE_EVENTO { ;
      { "**", "3.00P", "https://mdfe.svrs.rs.gov.br/ws/MDFeRecepcaoEvento/MDFeRecepcaoEvento.asmx" }, ;
      { "**", "3.00H", "https://mdfe-homologacao.svrs.rs.gov.br/ws/MDFeRecepcaoEvento/MDFeRecepcaoEvento.asmx" } }

#define WS_MDFE_ENVIALOTE { ;
      { "**", "3.00P", "https://mdfe.svrs.rs.gov.br/ws/MDFerecepcao/MDFeRecepcao.asmx" }, ;
      { "**", "3.00H", "https://mdfe-homologacao.svrs.rs.gov.br/ws/MDFerecepcao/MDFeRecepcao.asmx" } }

#define WS_MDFE_STATUSSERVICO { ;
      { "**", "3.00P", "https://mdfe.svrs.rs.gov.br/ws/MDFeStatusServico/MDFeStatusServico.asmx" }, ;
      ;
      { "**", "3.00H", "https://mdfe-homologacao.svrs.rs.gov.br/ws/MDFeStatusServico/MDFeStatusServico.asmx" } }

#define WS_NFE_CONSULTACADASTRO { ;
      { "BA",    "3.10P", "https://nfe.sefaz.ba.gov.br/webservices/nfenw/CadConsultaCadastro2.asmx" }, ;
      { "CE",    "3.10P", "https://nfe.sefaz.ce.gov.br/nfe2/services/CadConsultaCadastro2?wsdl" }, ;
      { "ES",    "3.10P", "https://app.sefaz.es.gov.br/ConsultaCadastroService/CadConsultaCadastro2.asmx" }, ;
      { "GO",    "3.10P", "https://nfe.sefaz.go.gov.br/nfe/services/v2/CadConsultaCadastro2?wsdl" }, ;
      { "MA",    "3.10P", "https://sistemas.sefaz.ma.gov.br/wscadastro/CadConsultaCadastro2?wsdl" }, ;
      { "MG",    "3.10P", "https://nfe.fazenda.mg.gov.br/nfe2/services/cadconsultacadastro2" }, ;
      { "MS",    "3.10P", "https://nfe.fazenda.ms.gov.br/producao/services2/CadConsultaCadastro2" }, ;
      { "MT",    "3.10P", "https://nfe.sefaz.mt.gov.br/nfews/v2/services/CadConsultaCadastro2?wsdl" }, ;
      { "PE",    "3.10P", "https://nfe.sefaz.pe.gov.br/nfe-service/services/CadConsultaCadastro2" }, ;
      { "PR",    "3.10P", "https://nfe.fazenda.pr.gov.br/nfe/CadConsultaCadastro2?wsdl" }, ;
      { "RS",    "3.10P", "https://cad.sefazrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx" }, ;
      { "SP",    "3.10P", "https://nfe.fazenda.sp.gov.br/ws/cadconsultacadastro2.asmx" }, ;
      { "SVRS",  "3.10P", "https://cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx" }, ;
      { "AC",    "3.10P", "https://cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx" }, ;
      { "RN",    "3.10P", "https://cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx" }, ;
      { "PB",    "3.10P", "https://cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx" }, ;
      { "SC",    "3.10P", "https://cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx" }, ;
      ;
      { "AM",    "3.10H", "https://homnfe.sefaz.am.gov.br/services2/services/CadConsultaCadastro2" }, ;
      { "BA",    "3.10H", "https://hnfe.sefaz.ba.gov.br/webservices/nfenw/CadConsultaCadastro2.asmx" }, ;
      { "CE",    "3.10H", "https://nfeh.sefaz.ce.gov.br/nfe2/services/CadConsultaCadastro2?wsdl" }, ;
      { "ES",    "3.10H", "https://app.sefaz.es.gov.br/ConsultaCadastroService/CadConsultaCadastro2.asmx" }, ;
      { "GO",    "3.10H", "https://homolog.sefaz.go.gov.br/nfe/services/v2/CadConsultaCadastro2?wsdl" }, ;
      { "MA",    "3.10H", "https://sistemas.sefaz.ma.gov.br/wscadastro/CadConsultaCadastro2?wsdl" }, ;
      { "MG",    "3.10H", "https://hnfe.fazenda.mg.gov.br/nfe2/services/cadconsultacadastro2" }, ;
      { "MS",    "3.10H", "https://homologacao.nfe.ms.gov.br/homologacao/services2/CadConsultaCadastro2" }, ;
      { "MT",    "3.10H", "https://homologacao.sefaz.mt.gov.br/nfews/v2/services/CadConsultaCadastro2?wsdl" }, ;
      { "PE",    "3.10H", "https://nfe.sefaz.pe.gov.br/nfe-service/services/NfeConsulta2" }, ;
      { "PR",    "3.10H", "https://homologacao.nfe.fazenda.pr.gov.br/nfe/CadConsultaCadastro2?wsdl" }, ;
      { "RS",    "3.10H", "https://cad.sefazrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx" }, ;
      { "SP",    "3.10H", "https://homologacao.nfe.fazenda.sp.gov.br/ws/cadconsultacadastro2.asmx" }, ;
      { "SVRS",  "3.10H", "https://cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx" }, ;
      { "AC",    "3.10H", "https://cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx" }, ;
      { "RN",    "3.10H", "https://cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx" }, ;
      { "PB",    "3.10H", "https://cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx" }, ;
      { "SC",    "3.10H", "https://cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx" }, ;
      ;
      { "SP",    "4.00P", "https://nfe.fazenda.sp.gov.br/ws/cadconsultacadastro4.asmx" }, ;
      ;
      { "SP",    "4.00H", "https://homologacao.nfe.fazenda.sp.gov.br/ws/cadconsultacadastro4.asmx" } }

#define WS_NFE_CONSULTADEST { ;
      { "RS",    "3.10P", "https://nfe.sefazrs.rs.gov.br/ws/nfeConsultaDest/nfeConsultaDest.asmx" }, ;
      { "AN",    "3.10P", "https://www.nfe.fazenda.gov.br/NFeConsultaDest/NFeConsultaDest.asmx" }, ;
      ;
      { "RS",    "3.10H", "https://nfe-homologacao.sefazrs.rs.gov.br/ws/nfeConsultaDest/nfeConsultaDest.asmx" } }

#define WS_NFE_CONSULTAPROTOCOLO { ;
      { "AM",    "3.10P", "https://nfe.sefaz.am.gov.br/services2/services/NfeConsulta2" }, ;
      { "BA",    "3.10P", "https://nfe.sefaz.ba.gov.br/webservices/NfeConsulta/NfeConsulta.asmx" }, ;
      { "CE",    "3.10P", "https://nfe.sefaz.ce.gov.br/nfe2/services/NfeConsulta2?wsdl" }, ;
      { "GO",    "3.10P", "https://nfe.sefaz.go.gov.br/nfe/services/v2/NfeConsulta2?wsdl" }, ;
      { "MG",    "3.10P", "https://nfe.fazenda.mg.gov.br/nfe2/services/NfeConsulta2" }, ;
      { "MS",    "3.10P", "https://nfe.fazenda.ms.gov.br/producao/services2/NfeConsulta2" }, ;
      { "MT",    "3.10P", "https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeConsulta2?wsdl" }, ;
      { "PE",    "3.10P", "https://nfe.sefaz.pe.gov.br/nfe-service/services/NfeConsulta2" }, ;
      { "PR",    "3.10P", "https://nfe.fazenda.pr.gov.br/nfe/NFeConsulta3?wsdl" }, ;
      { "RS",    "3.10P", "https://nfe.sefazrs.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx" }, ;
      { "SP",    "3.10P", "https://nfe.fazenda.sp.gov.br/ws/nfeconsulta2.asmx" }, ;
      { "SVRS",  "3.10P", "https://nfe.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx" }, ;
      { "SCAN",  "3.10P", "https://www.scan.fazenda.gov.br/NfeConsulta2/NfeConsulta2.asmx" }, ;
      { "SVAN",  "3.10P", "https://www.sefazvirtual.fazenda.gov.br/NfeConsulta2/NfeConsulta2.asmx" }, ;
      { "SCVAN", "3.10P", "https://www.svc.fazenda.gov.br/NfeConsulta2/NfeConsulta2.asmx" }, ;
      ;
      { "AM",    "3.10H", "https://homnfe.sefaz.am.gov.br/services2/services/NfeConsulta2" }, ;
      { "BA",    "3.10H", "https://hnfe.sefaz.ba.gov.br/webservices/nfenw/NfeConsulta2.asmx" }, ;
      { "CE",    "3.10H", "https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeConsulta2?wsdl" }, ;
      { "GO",    "3.10H", "https://homolog.sefaz.go.gov.br/nfe/services/v2/NfeConsulta2?wsdl" }, ;
      { "MG",    "3.10H", "https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeConsulta2" }, ;
      { "MT",    "3.10H", "https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeConsulta2?wsdl" }, ;
      { "MS",    "3.10H", "https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeConsulta2" }, ;
      { "PE",    "3.10H", "https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NfeConsulta2" }, ;
      { "PR",    "3.10H", "https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeConsulta3?wsdl" }, ;
      { "RS",    "3.10H", "https://nfe-homologacao.sefazrs.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx" }, ;
      { "SP",    "3.10H", "https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeconsulta2.asmx" }, ;
      { "SVRS",  "3.10H", "https://nfe-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx" }, ;
      { "SCAN",  "3.10H", "https://hom.nfe.fazenda.gov.br/SCAN/NfeConsulta2/NfeConsulta2.asmx" }, ;
      { "SVAN",  "3.10H", "https://hom.sefazvirtual.fazenda.gov.br/NfeConsulta2/NfeConsulta2.asmx" }, ;
      ;
      { "PR",   "3.10PC", "https://nfce.fazenda.pr.gov.br/nfce/NFeConsulta3" }, ;
      { "SVRS", "3.10PC", "https://nfce.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx" }, ;
      ;
      { "PR",   "3.10HC", "https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeConsulta3" }, ;
      { "SVRS", "3.10HC", "https://nfce-homologacao.svrs.rs.gov.br/ws/NfeConsulta/NfeConsulta2.asmx" }, ;
      ;
      { "MG",   "4.00P", "https://nfe.fazenda.mg.gov.br/nfe2/services/NFeConsultaProtocolo4" }, ;
      { "SP",   "4.00P", "https://nfe.fazenda.sp.gov.br/ws/nfeconsultaprotocolo4.asmx" }, ;
      ;
      { "MG",   "4.00H", "https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeConsultaProtocolo4" }, ;
      { "SP",   "4.00H", "https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeconsultaprotocolo4.asmx" } }

#define WS_NFE_DISTRIBUICAO { ;
      { "AN",    "3.10P", "https://www1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx" } }

#define WS_NFE_EVENTO { ;
      { "AM",    "3.10P", "https://nfe.sefaz.am.gov.br/services2/services/RecepcaoEvento" }, ;
      { "BA",    "3.10P", "https://nfe.sefaz.ba.gov.br/webservices/sre/RecepcaoEvento.asmx" }, ;
      { "CE",    "3.10P", "https://nfe.sefaz.ce.gov.br/nfe2/services/RecepcaoEvento?wsdl" }, ;
      { "GO",    "3.10P", "https://nfe.sefaz.go.gov.br/nfe/services/v2/RecepcaoEvento?wsdl" }, ;
      { "MG",    "3.10P", "https://nfe.fazenda.mg.gov.br/nfe2/services/RecepcaoEvento" }, ;
      { "MS",    "3.10P", "https://nfe.fazenda.ms.gov.br/producao/services2/RecepcaoEvento" }, ;
      { "MT",    "3.10P", "https://nfe.sefaz.mt.gov.br/nfews/v2/services/RecepcaoEvento?wsdl" }, ;
      { "PE",    "3.10P", "https://nfe.sefaz.pe.gov.br/nfe-service/services/RecepcaoEvento" }, ;
      { "PR",    "3.10P", "https://nfe2.fazenda.pr.gov.br/nfe-evento/NFeRecepcaoEvento?wsdl" }, ;
      { "RS",    "3.10P", "https://nfe.sefazrs.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx" }, ;
      { "SP",    "3.10P", "https://nfe.fazenda.sp.gov.br/ws/recepcaoevento.asmx" }, ;
      { "SVRS",  "3.10P", "https://nfe.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx" }, ;
      { "SCAN",  "3.10P", "https://www.scan.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx" }, ;
      { "SVAN",  "3.10P", "https://www.sefazvirtual.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx" }, ;
      { "SCVAN", "3.10P", "https://www.svc.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx" }, ;
      { "AN",    "3.10P", "https://www.nfe.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx" }, ;
      ;
      { "AM",    "3.10H", "https://homnfe.sefaz.am.gov.br/services2/services/RecepcaoEvento" }, ;
      { "BA",    "3.10H", "https://hnfe.sefaz.ba.gov.br/webservices/sre/RecepcaoEvento.asmx" }, ;
      { "CE",    "3.10H", "https://nfeh.sefaz.ce.gov.br/nfe2/services/RecepcaoEvento?wsdl" }, ;
      { "GO",    "3.10H", "https://homolog.sefaz.go.gov.br/nfe/services/v2/NfeRecepcaoEvento?wsdl" }, ;
      { "MG",    "3.10H", "https://hnfe.fazenda.mg.gov.br/nfe2/services/RecepcaoEvento" }, ;
      { "MS",    "3.10H", "https://homologacao.nfe.ms.gov.br/homologacao/services2/RecepcaoEvento" }, ;
      { "MT",    "3.10H", "https://homologacao.sefaz.mt.gov.br/nfews/v2/services/RecepcaoEvento?wsdl" }, ;
      { "PE",    "3.10H", "https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/RecepcaoEvento" }, ;
      { "PR",    "3.10H", "https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeRecepcaoEvento?wsdl" }, ;
      { "RS",    "3.10H", "https://nfe-homologacao.sefazrs.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx" }, ;
      { "SP",    "3.10H", "https://homologacao.nfe.fazenda.sp.gov.br/ws/recepcaoevento.asmx" }, ;
      { "SVRS",  "3.10H", "https://nfe-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx" }, ;
      { "SVAN",  "3.10H", "https://hom.sefazvirtual.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx" }, ;
      ;
      { "PR",   "3.10PC", "https://nfce.fazenda.pr.gov.br/nfce/NFeRecepcaoEvento" }, ;
      { "SVRS", "3.10PC", "https://nfce.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx" }, ;
      ;
      { "PR",   "3.10HC", "https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeRecepcaoEvento" }, ;
      { "SVRS", "3.10HC", "https://nfce-homologacao.svrs.rs.gov.br/ws/recepcaoevento/recepcaoevento.asmx" }, ;
      ;
      { "MG",   "4.00P", "https://nfe.fazenda.mg.gov.br/nfe2/services/NFeRecepcaoEvento4 " }, ;
      { "SP",   "4.00P", "https://nfe.fazenda.sp.gov.br/ws/nferecepcaoevento4.asmx" }, ;
      ;
      { "MG",   "4.00H", "https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeRecepcaoEvento4 " }, ;
      { "SP",   "4.00H", "https://homologacao.nfe.fazenda.sp.gov.br/ws/nferecepcaoevento4.asmx" } }

#define WS_NFE_INUTILIZA { ;
      { "AM",    "3.10P", "https://nfe.sefaz.am.gov.br/services2/services/NfeInutilizacao2" }, ;
      { "BA",    "3.10P", "https://nfe.sefaz.ba.gov.br/webservices/NfeInutilizacao/NfeInutilizacao.asmx" }, ;
      { "CE",    "3.10P", "https://nfe.sefaz.ce.gov.br/nfe2/services/NfeInutilizacao2?wsdl" }, ;
      { "GO",    "3.10P", "https://nfe.sefaz.go.gov.br/nfe/services/v2/NfeInutilizacao2?wsdl" }, ;
      { "MG",    "3.10P", "https://nfe.fazenda.mg.gov.br/nfe2/services/NfeInutilizacao2" }, ;
      { "MS",    "3.10P", "https://nfe.fazenda.ms.gov.br/producao/services2/NfeInutilizacao2" }, ;
      { "MT",    "3.10P", "https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeInutilizacao2?wsdl" }, ;
      { "PE",    "3.10P", "https://nfe.sefaz.pe.gov.br/nfe-service/services/NfeInutilizacao2" }, ;
      { "PR",    "3.10P", "https://nfe.fazenda.pr.gov.br/nfe/NFeInutilizacao3?wsdl" }, ;
      { "RS",    "3.10P", "https://nfe.sefazrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx" }, ;
      { "SP",    "3.10P", "https://nfe.fazenda.sp.gov.br/ws/nfeinutilizacao2.asmx" }, ;
      { "SVRS",  "3.10P", "https://nfe.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx" }, ;
      { "SCAN",  "3.10P", "https://www.scan.fazenda.gov.br/NfeInutilizacao2/NfeInutilizacao2.asmx" }, ;
      { "SVAN",  "3.10P", "https://www.sefazvirtual.fazenda.gov.br/NfeInutilizacao2/NfeInutilizacao2.asmx" }, ;
      ;
      { "AM",    "3.10H", "https://homnfe.sefaz.am.gov.br/services2/services/NfeInutilizacao2" }, ;
      { "BA",    "3.10H", "https://hnfe.sefaz.ba.gov.br/webservices/nfenw/NfeInutilizacao2.asmx" }, ;
      { "CE",    "3.10H", "https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeInutilizacao2?wsdl" }, ;
      { "GO",    "3.10H", "https://homolog.sefaz.go.gov.br/nfe/services/v2/NfeInutilizacao2?wsdl" }, ;
      { "MG",    "3.10H", "https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeInutilizacao2" }, ;
      { "MS",    "3.10H", "https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeInutilizacao2" }, ;
      { "MT",    "3.10H", "https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeInutilizacao2?wsdl" }, ;
      { "PE",    "3.10H", "https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NfeInutilizacao2" }, ;
      { "PR",    "3.10H", "https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeInutilizacao3?wsdl" }, ;
      { "RS",    "3.10H", "https://nfe-homologacao.sefazrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx" }, ;
      { "SP",    "3.10H", "https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeinutilizacao2.asmx" }, ;
      { "SVRS",  "3.10H", "https://nfe-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx" }, ;
      { "SCAN",  "3.10H", "https://hom.nfe.fazenda.gov.br/SCAN/NfeInutilizacao2/NfeInutilizacao2.asmx" }, ;
      { "SVAN",  "3.10H", "https://hom.sefazvirtual.fazenda.gov.br/NfeInutilizacao2/NfeInutilizacao2.asmx" }, ;
      ;
      { "PR",   "3.10PC", "https://nfce.fazenda.pr.gov.br/nfce/NFeInutilizacao3" }, ;
      { "SVRS", "3.10PC", "https://nfce.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx" }, ;
      ;
      { "PR",   "3.10HC", "https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeInutilizacao3" }, ;
      { "SVRS", "3.10HC", "https://nfce-homologacao.svrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao2.asmx" }, ;
      ;
      { "MG", "4.00P", "https://nfe.fazenda.mg.gov.br/nfe2/services/NFeInutilizacao4" }, ;
      { "SP", "4.00P", "https://nfe.fazenda.sp.gov.br/ws/nfeinutilizacao4.asmx" }, ;
      ;
      { "MG", "4.00H", "https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeInutilizacao4" }, ;
      { "SP", "4.00H", "https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeinutilizacao4.asmx" } }

#define WS_NFE_ENVIALOTE { ;
      { "AM",    "3.10P", "https://nfe.sefaz.am.gov.br/services2/services/NfeAutorizacao" }, ;
      { "BA",    "3.10P", "https://nfe.sefaz.ba.gov.br/webservices/NfeAutorizacao/NfeAutorizacao.asmx" }, ;
      { "CE",    "3.10P", "https://nfe.sefaz.ce.gov.br/nfe2/services/NfeAutorizacao?wsdl" }, ;
      { "GO",    "3.10P", "https://nfe.sefaz.go.gov.br/nfe/services/v2/NfeAutorizacao?wsdl" }, ;
      { "MG",    "3.10P", "https://nfe.fazenda.mg.gov.br/nfe2/services/NfeAutorizacao" }, ;
      { "MS",    "3.10P", "https://nfe.fazenda.ms.gov.br/producao/services2/NfeAutorizacao" }, ;
      { "MT",    "3.10P", "https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeAutorizacao?wsdl" }, ;
      { "PE",    "3.10P", "https://nfe.sefaz.pe.gov.br/nfe-service/services/NfeAutorizacao?wsdl" }, ;
      { "PR",    "3.10P", "https://nfe.fazenda.pr.gov.br/nfe/NFeAutorizacao3?wsdl" }, ;
      { "RS",    "3.10P", "https://nfe.sefazrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx" }, ;
      { "SP",    "3.10P", "https://nfe.fazenda.sp.gov.br/ws/nfeautorizacao.asmx" }, ;
      { "SVRS",  "3.10P", "https://nfe.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx" }, ;
      { "SCAN",  "3.10P", "https://www.scan.fazenda.gov.br/NfeAutorizacao/NfeAutorizacao.asmx" }, ;
      { "SCVAN", "3.10P", "https://www.svc.fazenda.gov.br/NfeAutorizacao/NfeAutorizacao.asmx" }, ;
      { "SVAN",  "3.10P", "https://www.sefazvirtual.fazenda.gov.br/NfeAutorizacao/NfeAutorizacao.asmx" }, ;
      ;
      { "CE",    "3.10H", "https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeAutorizacao?wsdl" }, ;
      { "MG",    "3.10H", "https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeAutorizacao" }, ;
      { "PR",    "3.10H", "https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeAutorizacao3?wsdl" }, ;
      { "RS",    "3.10H", "https://nfe-homologacao.sefazrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx" }, ;
      { "SP",    "3.10H", "https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeautorizacao.asmx" }, ;
      { "SVRS",  "3.10H", "https://nfe-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx" }, ;
   ;
      { "PR",   "3.10PC", "https://nfce.fazenda.pr.gov.br/nfce/NFeAutorizacao3" }, ;
      { "SVRS", "3.10PC", "https://nfce.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx" }, ;
      ;
      { "PR",   "3.10HC", "https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeAutorizacao3" }, ;
      { "SVRS", "3.10HC", "https://nfce-homologacao.svrs.rs.gov.br/ws/NfeAutorizacao/NFeAutorizacao.asmx" }, ;
   ;
      { "MG", "4.00P", "https://nfe.fazenda.mg.gov.br/nfe2/services/NFeAutorizacao4" }, ;
      { "SP", "4.00P", "https://nfe.fazenda.sp.gov.br/ws/nfeautorizacao4.asmx" }, ;
      ;
      { "MG", "4.00H", "https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeAutorizacao4" }, ;
      { "SP", "4.00H", "https://homologacao.nfe.fazenda.sp.gov.br/ws/nfeautorizacao4.asmx" } }

#define WS_NFE_CONSULTARECIBO { ;
      { "AM",    "3.10P", "https://nfe.sefaz.am.gov.br/services2/services/NfeRetAutorizacao" }, ;
      { "BA",    "3.10P", "https://nfe.sefaz.ba.gov.br/webservices/NfeRetAutorizacao/NfeRetAutorizacao.asmx" }, ;
      { "CE",    "3.10P", "https://nfe.sefaz.ce.gov.br/nfe2/services/NfeRetAutorizacao?wsdl" }, ;
      { "GO",    "3.10P", "https://nfe.sefaz.go.gov.br/nfe/services/v2/NfeRetAutorizacao?wsdl" }, ;
      { "MG",    "3.10P", "https://nfe.fazenda.mg.gov.br/nfe2/services/NfeRetAutorizacao" }, ;
      { "MS",    "3.10P", "https://nfe.fazenda.ms.gov.br/producao/services2/NfeRetAutorizacao" }, ;
      { "MT",    "3.10P", "https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeRetAutorizacao?wsdl" }, ;
      { "PE",    "3.10P", "https://nfe.sefaz.pe.gov.br/nfe-service/services/NfeRetAutorizacao?wsdl" }, ;
      { "PR",    "3.10P", "https://nfe.fazenda.pr.gov.br/nfe/NFeRetAutorizacao3?wsdl" }, ;
      { "RS",    "3.10P", "https://nfe.sefazrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao.asmx" }, ;
      { "SP",    "3.10P", "https://nfe.fazenda.sp.gov.br/ws/nferetautorizacao.asmx" }, ;
      { "SCAN",  "3.10P", "https://www.scan.fazenda.gov.br/NfeRetAutorizacao/NfeRetAutorizacao.asmx" }, ;
      { "SVRS",  "3.10P", "https://nfe.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao.asmx" }, ;
      { "SVAN",  "3.10P", "https://www.sefazvirtual.fazenda.gov.br/NfeRetAutorizacao/NfeRetAutorizacao.asmx" }, ;
      { "SCVAN", "3.10P", "https://www.svc.fazenda.gov.br/NfeRetAutorizacao/NfeRetAutorizacao.asmx" }, ;
      ;
      { "CE",    "3.10H", "https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeRetAutorizacao?wsdl" }, ;
      { "MG",    "3.10H", "https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeRetAutorizacao" }, ;
      { "PR",    "3.10H", "https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeRetAutorizacao3?wsdl" }, ;
      { "RS",    "3.10H", "https://nfe-homologacao.sefazrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao.asmx" }, ;
      { "SP",    "3.10H", "https://homologacao.nfe.fazenda.sp.gov.br/ws/nferetautorizacao.asmx" }, ;
      { "SVRS",  "3.10H", "https://nfe-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao.asmx" }, ;
      ;
      { "PR",   "3.10PC", "https://nfce.fazenda.pr.gov.br/nfce/NFeRetAutorizacao3" }, ;
      { "SVRS", "3.10PC", "https://nfce.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao.asmx" }, ;
      ;
      { "PR",   "3.10HC", "https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeRetAutorizacao3" }, ;
      { "SVRS", "3.10HC", "https://nfce-homologacao.svrs.rs.gov.br/ws/NfeRetAutorizacao/NFeRetAutorizacao.asmx" }, ;
      ;
      { "MG", "4.00P", "https://nfe.fazenda.mg.gov.br/nfe2/services/NFeRetAutorizacao4" }, ;
      { "SP", "4.00P", "https://nfe.fazenda.sp.gov.br/ws/nferetautorizacao4.asmx" }, ;
      ;
      { "MG", "4.00H", "https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeRetAutorizacao4" }, ;
      { "SP", "4.00H", "https://homologacao.nfe.fazenda.sp.gov.br/ws/nferetautorizacao4.asmx" } }

#define WS_NFE_STATUSSERVICO { ;
      { "AM",    "3.10P", "https://nfe.sefaz.am.gov.br/services2/services/NfeStatusServico2" }, ;
      { "BA",    "3.10P", "https://nfe.sefaz.ba.gov.br/webservices/NfeStatusServico/NfeStatusServico.asmx" }, ;
      { "CE",    "3.10P", "https://nfe.sefaz.ce.gov.br/nfe2/services/NfeStatusServico2?wsdl" }, ;
      { "GO",    "3.10P", "https://nfe.sefaz.go.gov.br/nfe/services/v2/NfeStatusServico2?wsdl" }, ;
      { "MG",    "3.10P", "https://nfe.fazenda.mg.gov.br/nfe2/services/NfeStatus2" }, ;
      { "MS",    "3.10P", "https://nfe.fazenda.ms.gov.br/producao/services2/NfeStatusServico2" }, ;
      { "MT",    "3.10P", "https://nfe.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico2?wsdl" }, ;
      { "PE",    "3.10P", "https://nfe.sefaz.pe.gov.br/nfe-service/services/NfeStatusServico2" }, ;
      { "PR",    "3.10P", "https://nfe.fazenda.pr.gov.br/nfe/NFeStatusServico3?wsdl" }, ;
      { "RS",    "3.10P", "https://nfe.sefazrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx" }, ;
      { "SP",    "3.10P", "https://nfe.fazenda.sp.gov.br/ws/nfestatusservico2.asmx" }, ;
      { "SVRS",  "3.10P", "https://nfe.svrs.rs.gov.br/ws/nfeStatusServico/NfeStatusServico2.asmx" }, ;
      { "SCAN",  "3.10P", "https://www.scan.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx" }, ;
      { "SVAN",  "3.10P", "https://www.sefazvirtual.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx" }, ;
      { "SCVAN", "3.10P", "https://www.svc.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx" }, ;
      ;
      { "AM",    "3.10H", "https://homnfe.sefaz.am.gov.br/services2/services/NfeStatusServico2" }, ;
      { "BA",    "3.10H", "https://hnfe.sefaz.ba.gov.br/webservices/NfeStatusServico/NfeStatusServico.asmx" }, ;
      { "CE",    "3.10H", "https://nfeh.sefaz.ce.gov.br/nfe2/services/NfeStatusServico2?wsdl" }, ;
      { "GO",    "3.10H", "https://homolog.sefaz.go.gov.br/nfe/services/v2/NfeStatusServico2?wsdl" }, ;
      { "MG",    "3.10H", "https://hnfe.fazenda.mg.gov.br/nfe2/services/NfeStatusServico2" }, ;
      { "MS",    "3.10H", "https://homologacao.nfe.ms.gov.br/homologacao/services2/NfeStatusServico2" }, ;
      { "MT",    "3.10H", "https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico2?wsdl" }, ;
      { "PE",    "3.10H", "https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NfeStatusServico2" }, ;
      { "PR",    "3.10H", "https://homologacao.nfe.fazenda.pr.gov.br/nfe/NFeStatusServico3?wsdl" }, ;
      { "RS",    "3.10H", "https://nfe-homologacao.sefazrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx" }, ;
      { "SP",    "3.10H", "https://homologacao.nfe.fazenda.sp.gov.br/ws/nfestatusservico2.asmx" }, ;
      { "SVRS",  "3.10H", "https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx" }, ;
      { "SCAN",  "3.10H", "https://hom.nfe.fazenda.gov.br/SCAN/NfeStatusServico2/NfeStatusServico2.asmx" }, ;
      { "SVAN",  "3.10H", "https://hom.sefazvirtual.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx" }, ;
      ;
      { "PR",   "3.10PC", "https://nfce.fazenda.pr.gov.br/nfce/NFeStatusServico3" }, ;
      { "SVRS", "3.10PC", "https://nfce.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx" }, ;
      ;
      { "PR",   "3.10HC", "https://homologacao.nfce.fazenda.pr.gov.br/nfce/NFeStatusServico3" }, ;
      { "SVRS", "3.10HC", "https://nfce-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico2.asmx" }, ;
      ;
      { "MG", "4.00P", "https://nfe.fazenda.mg.gov.br/nfe2/services/NFeStatusServico4" }, ;
      { "SP", "4.00P", "https://nfe.fazenda.sp.gov.br/ws/nfestatusservico4.asmx" }, ;
      ;
      { "MG", "4.00H", "https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeStatusServico4" }, ;
      { "SP", "4.00H", "https://homologacao.nfe.fazenda.sp.gov.br/ws/nfestatusservico4.asmx" } }

#define WS_NFE_QRCODE { ;
      { "AC", "3.10P", "http://www.sefaznet.ac.gov.br/nfce/qrcode?" }, ;
      { "AL", "3.10P", "http://nfce.sefaz.al.gov.br/QRCode/consultarNFCe.jsp?" }, ;
      { "AP", "3.10P", "https://www.sefaz.ap.gov.br/nfce/nfcep.php?" }, ;
      { "AM", "3.10P", "http://sistemas.sefaz.am.gov.br/nfceweb/consultarNFCe.jsp?" }, ;
      { "BA", "3.10P", "http://nfe.sefaz.ba.gov.br/servicos/nfce/modulos/geral/NFCEC_consulta_chave_acesso.aspx" }, ;
      { "CE", "3.10P", "http://nfce.sefaz.ce.gov.br/pages/ShowNFCe.html" }, ;
      { "DF", "3.10P", "http://dec.fazenda.df.gov.br/ConsultarNFCe.aspx" }, ;
      { "ES", "3.10P", "http://app.sefaz.es.gov.br/ConsultaNFCe/qrcode.aspx?" }, ;
      { "GO", "3.10P", "http://nfe.sefaz.go.gov.br/nfeweb/sites/nfce/danfeNFCe" }, ;
      { "MA", "3.10P", "http://www.nfce.sefaz.ma.gov.br/portal/consultarNFCe.jsp?" }, ;
      { "MT", "3.10P", "http://www.sefaz.mt.gov.br/nfce/consultanfce?" }, ;
      { "MS", "3.10P", "http://www.dfe.ms.gov.br/nfce/qrcode?" }, ;
      { "MG", "3.10P", "" }, ;
      { "PA", "3.10P", "https://appnfc.sefa.pa.gov.br/portal/view/consultas/nfce/nfceForm.seam?" }, ;
      { "PB", "3.10P", "http://www.receita.pb.gov.br/nfce?" }, ;
      { "PR", "3.10P", "http://www.dfeportal.fazenda.pr.gov.br/dfe-portal/rest/servico/consultaNFCe?" }, ;
      { "PE", "3.10P", "http://nfce.sefaz.pe.gov.br/nfce-web/consultarNFCe?" }, ;
      { "PI", "3.10P", "http://webas.sefaz.pi.gov.br/nfceweb/consultarNFCe.jsf?" }, ;
      { "RJ", "3.10P", "http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode?" }, ;
      { "RN", "3.10P", "http://nfce.set.rn.gov.br/consultarNFCe.aspx?" }, ;
      { "RS", "3.10P", "https://www.sefaz.rs.gov.br/NFCE/NFCE-COM.aspx?" }, ;
      { "RO", "3.10P", "http://www.nfce.sefin.ro.gov.br/consultanfce/consulta.jsp?" }, ;
      { "RR", "3.10P", "https://www.sefaz.rr.gov.br/nfce/servlet/qrcode?" }, ;
      { "SC", "3.10P", "" }, ;
      { "SP", "3.10P", "https://www.nfce.fazenda.sp.gov.br/NFCeConsultaPublica/Paginas/ConsultaQRCode.aspx?" }, ;
      { "SE", "3.10P", "http://www.nfce.se.gov.br/portal/consultarNFCe.jsp?" }, ;
      { "TO", "3.10P", "" }, ;
      ;
      { "AC", "3.10H", "http://www.hml.sefaznet.ac.gov.br/nfce/qrcode?" }, ;
      { "AL", "3.10H", "http://nfce.sefaz.al.gov.br/QRCode/consultarNFCe.jsp?" }, ;
      { "AP", "3.10H", "https://www.sefaz.ap.gov.br/nfcehml/nfce.php?" }, ;
      { "AM", "3.10H", "http://homnfce.sefaz.am.gov.br/nfceweb/consultarNFCe.jsp?" }, ;
      { "BA", "3.10H", "http://hnfe.sefaz.ba.gov.br/servicos/nfce/modulos/geral/NFCEC_consulta_chave_acesso.aspx" }, ;
      { "CE", "3.10H", "http://nfceh.sefaz.ce.gov.br/pages/ShowNFCe.html" }, ;
      { "DF", "3.10H", "http://dec.fazenda.df.gov.br/ConsultarNFCe.aspx" }, ;
      { "ES", "3.10H", "http://homologacao.sefaz.es.gov.br/ConsultaNFCe/qrcode.aspx?" }, ;
      { "GO", "3.10H", "" }, ;
      { "MA", "3.10H", "http://www.hom.nfce.sefaz.ma.gov.br/portal/consultarNFCe.jsp?" }, ;
      { "MT", "3.10H", "http://homologacao.sefaz.mt.gov.br/nfce/consultanfce?" }, ;
      { "MS", "3.10H", "http://www.dfe.ms.gov.br/nfce/qrcode?" }, ;
      { "MG", "3.10H", "" }, ;
      { "PA", "3.10H", "https://appnfc.sefa.pa.gov.br/portal-homologacao/view/consultas/nfce/nfceForm.seam" }, ;
      { "PB", "3.10H", "http://www.receita.pb.gov.br/nfcehom" }, ;
      { "PR", "3.10H", "http://www.dfeportal.fazenda.pr.gov.br/dfe-portal/rest/servico/consultaNFCe?" }, ;
      { "PE", "3.10H", "http://nfcehomolog.sefaz.pe.gov.br/nfce-web/consultarNFCe?" }, ;
      { "PI", "3.10H", "http://webas.sefaz.pi.gov.br/nfceweb-homologacao/consultarNFCe.jsf?" }, ;
      { "RJ", "3.10H", "http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode?" }, ;
      { "RN", "3.10H", "http://hom.nfce.set.rn.gov.br/consultarNFCe.aspx?" }, ;
      { "RS", "3.10H", "https://www.sefaz.rs.gov.br/NFCE/NFCE-COM.aspx?" }, ;
      { "RO", "3.10H", "http://www.nfce.sefin.ro.gov.br/consultanfce/consulta.jsp?" }, ;
      { "RR", "3.10H", "http://200.174.88.103:8080/nfce/servlet/qrcode?" }, ;
      { "SC", "3.10H", "" }, ;
      { "SP", "3.10H", "https://www.homologacao.nfce.fazenda.sp.gov.br/NFCeConsultaPublica/Paginas/ConsultaQRCode.aspx" }, ;
      { "SE", "3.10H", "http://www.hom.nfe.se.gov.br/portal/consultarNFCe.jsp?" }, ;
      { "TO", "3.10H", "" } }

/*
#define SEFAZ_STATUSLIST { ;
      { "100", "Autorizado o uso da NF-e" }, ;
      { "101", "Cancelamento de NF-e homologado" }, ;
      { "102", "Inutilização de número homologado" }, ;
      { "103", "Lote recebido com sucesso" }, ;
      { "104", "Lote processado" }, ;
      { "105", "Lote em processamento" }, ;
      { "106", "Lote não localizado" }, ;
      { "107", "Serviço em Operação" }, ;
      { "108", "Serviço Paralisado Momentaneamente (curto prazo)" }, ;
      { "109", "Serviço Paralisado sem Previsão" }, ;
      { "110", "Uso Denegado" }, ;
      { "111", "Consulta cadastro com uma ocorrência" }, ;
      { "112", "Consulta cadastro com mais de uma ocorrência" }, ;
      { "124", "EPEC Autorizado" }, ;
      { "128", "Lote de Evento Processado" }, ;
      { "135", "Evento registrado e vinculado a NF-e" }, ;
      { "136", "Evento registrado, mas não vinculado a NF-e" }, ;
      { "137", "Nenhum documento localizado para o Destinatário" }, ;
      { "138", "Documento localizado para o Destinatário" }, ;
      { "139", "Pedido de Download processado" }, ;
      { "140", "Download disponibilizado" }, ;
      { "142", "Ambiente de Contingência EPEC bloqueado para o Emitente" }, ;
      { "150", "Autorizado o uso da NF-e, autorização fora de prazo" }, ;
      { "151", "Cancelamento de NF-e homologado fora de prazo" }, ;
      { "201", "Rejeição: Número máximo de numeração a inutilizar ultrapassou o limite" }, ;
      { "202", "Rejeição: Falha no reconhecimento da autoria ou integridade do arquivo digital" }, ;
      { "203", "Rejeição: Emissor não habilitado para emissão de NF-e" }, ;
      { "204", "Duplicidade de NF-e [nRec:999999999999999]" }, ;
      { "205", "NF-e está denegada na base de dados da SEFAZ [nRec:999999999999999]" }, ;
      { "206", "Rejeição: NF-e já está inutilizada na Base de dados da SEFAZ" }, ;
      { "207", "Rejeição: CNPJ do emitente inválido" }, ;
      { "208", "Rejeição: CNPJ do destinatário inválido" }, ;
      { "209", "Rejeição: IE do emitente inválida" }, ;
      { "210", "Rejeição: IE do destinatário inválida" }, ;
      { "211", "Rejeição: IE do substituto inválida" }, ;
      { "212", "Rejeição: Data de emissão NF-e posterior a data de recebimento" }, ;
      { "213", "Rejeição: CNPJ-Base do Emitente difere do CNPJ-Base do Certificado Digital" }, ;
      { "214", "Rejeição: Tamanho da mensagem excedeu o limite estabelecido" }, ;
      { "215", "Rejeição: Falha no schema XML" }, ;
      { "216", "Rejeição: Chave de Acesso difere da cadastrada" }, ;
      { "217", "Rejeição: NF-e não consta na base de dados da SEFAZ" }, ;
      { "218", "NF-e já está cancelada na base de dados da SEFAZ [nRec:999999999999999]" }, ;
      { "219", "Rejeição: Circulação da NF-e verificada" }, ;
      { "220", "Rejeição: Prazo de Cancelamento superior ao previsto na Legislação" }, ;
      { "221", "Rejeição: Confirmado o recebimento da NF-e pelo destinatário" }, ;
      { "222", "Rejeição: Protocolo de Autorização de Uso difere do cadastrado" }, ;
      { "223", "Rejeição: CNPJ do transmissor do lote difere do CNPJ do transmissor da consulta" }, ;
      { "224", "Rejeição: A faixa inicial é maior que a faixa final" }, ;
      { "225", "Rejeição: Falha no Schema XML do lote de NFe" }, ;
      { "226", "Rejeição: Código da UF do Emitente diverge da UF autorizadora" }, ;
      { "227", "Rejeição: Erro na Chave de Acesso – Campo Id – falta a literal NFe" }, ;
      { "228", "Rejeição: Data de Emissão muito atrasada" }, ;
      { "229", "Rejeição: IE do emitente não informada" }, ;
      { "230", "Rejeição: IE do emitente não cadastrada" }, ;
      { "231", "Rejeição: IE do emitente não vinculada ao CNPJ" }, ;
      { "232", "Rejeição: IE do destinatário não informada" }, ;
      { "233", "Rejeição: IE do destinatário não cadastrada" }, ;
      { "234", "Rejeição: IE do destinatário não vinculada ao CNPJ" }, ;
      { "235", "Rejeição: Inscrição SUFRAMA inválida" }, ;
      { "236", "Rejeição: Chave de Acesso com dígito verificador inválido" }, ;
      { "237", "Rejeição: CPF do destinatário inválido" }, ;
      { "238", "Rejeição: Cabeçalho – Versão do arquivo XML superior a Versão vigente" }, ;
      { "239", "Rejeição: Cabeçalho – Versão do arquivo XML não suportada" }, ;
      { "240", "Rejeição: Cancelamento/Inutilização – Irregularidade Fiscal do Emitente" }, ;
      { "241", "Rejeição: Um número da faixa já foi utilizado" }, ;
      { "242", "Rejeição: Cabeçalho – Falha no Schema XML" }, ;
      { "243", "Rejeição: XML Mal Formado" }, ;
      { "244", "Rejeição: CNPJ do Certificado Digital difere do CNPJ da Matriz e do CNPJ do Emitente" }, ;
      { "245", "Rejeição: CNPJ Emitente não cadastrado" }, ;
      { "246", "Rejeição: CNPJ Destinatário não cadastrado" }, ;
      { "247", "Rejeição: Sigla da UF do Emitente diverge da UF autorizadora" }, ;
      { "248", "Rejeição: UF do Recibo diverge da UF autorizadora" }, ;
      { "249", "Rejeição: UF da Chave de Acesso diverge da UF autorizadora" }, ;
      { "250", "Rejeição: UF diverge da UF autorizadora" }, ;
      { "251", "Rejeição: UF/Município destinatário não pertence a SUFRAMA" }, ;
      { "252", "Rejeição: Ambiente informado diverge do Ambiente de recebimento" }, ;
      { "253", "Rejeição: Digito Verificador da chave de acesso composta inválida" }, ;
      { "254", "Rejeição: NF-e complementar não possui NF referenciada" }, ;
      { "255", "Rejeição: NF-e complementar possui mais de uma NF referenciada" }, ;
      { "256", "Rejeição: Uma NF-e da faixa já está inutilizada na Base de dados da SEFAZ" }, ;
      { "257", "Rejeição: Solicitante não habilitado para emissão da NF-e" }, ;
      { "258", "Rejeição: CNPJ da consulta inválido" }, ;
      { "259", "Rejeição: CNPJ da consulta não cadastrado como contribuinte na UF" }, ;
      { "260", "Rejeição: IE da consulta inválida" }, ;
      { "261", "Rejeição: IE da consulta não cadastrada como contribuinte na UF" }, ;
      { "262", "Rejeição: UF não fornece consulta por CPF" }, ;
      { "263", "Rejeição: CPF da consulta inválido" }, ;
      { "264", "Rejeição: CPF da consulta não cadastrado como contribuinte na UF" }, ;
      { "265", "Rejeição: Sigla da UF da consulta difere da UF do Web Service" }, ;
      { "266", "Rejeição: Série utilizada não permitida no Web Service" }, ;
      { "267", "Rejeição: NF Complementar referencia uma NF-e inexistente" }, ;
      { "268", "Rejeição: NF Complementar referencia outra NF-e Complementar" }, ;
      { "269", "Rejeição: CNPJ Emitente da NF Complementar difere do CNPJ da NF Referenciada" }, ;
      { "270", "Rejeição: Código Município do Fato Gerador: dígito inválido" }, ;
      { "271", "Rejeição: Código Município do Fato Gerador: difere da UF do emitente" }, ;
      { "272", "Rejeição: Código Município do Emitente inexistente" }, ;
      { "273", "Rejeição: Código Município do Emitente: difere da UF do emitente" }, ;
      { "274", "Rejeição: Código Município do Destinatário inexistente" }, ;
      { "275", "Rejeição: Código Município do Destinatário: difere da UF do Destinatário" }, ;
      { "276", "Rejeição: Código Município do Local de Retirada inexistente" }, ;
      { "277", "Rejeição: Código Município do Local de Retirada: difere da UF do Local de Retirada" }, ;
      { "278", "Rejeição: Código Município do Local de Entrega inexistente" }, ;
      { "279", "Rejeição: Código Município do Local de Entrega: difere da UF do Local de Entrega" }, ;
      { "280", "Rejeição: Certificado Transmissor inválido" }, ;
      { "281", "Rejeição: Certificado Transmissor Data Validade" }, ;
      { "282", "Rejeição: Certificado Transmissor sem CNPJ" }, ;
      { "283", "Rejeição: Certificado Transmissor – erro Cadeia de Certificação" }, ;
      { "284", "Rejeição: Certificado Transmissor revogado" }, ;
      { "285", "Rejeição: Certificado Transmissor difere ICP-Brasil" }, ;
      { "286", "Rejeição: Certificado Transmissor erro no acesso a LCR" }, ;
      { "287", "Rejeição: Código Município do Fato Gerador de ISSQN inexistente [nItem:nnn]" }, ;
      { "288", "Rejeição: Código Município do Fato Gerador do Transporte inexistente" }, ;
      { "289", "Rejeição: Código da UF informada diverge da UF solicitada" }, ;
      { "290", "Rejeição: Certificado Assinatura inválido" }, ;
      { "291", "Rejeição: Certificado Assinatura Data Validade" }, ;
      { "292", "Rejeição: Certificado Assinatura sem CNPJ" }, ;
      { "293", "Rejeição: Certificado Assinatura – erro Cadeia de Certificação" }, ;
      { "294", "Rejeição: Certificado Assinatura revogado" }, ;
      { "295", "Rejeição: Certificado Assinatura difere ICP-Brasil" }, ;
      { "296", "Rejeição: Certificado Assinatura erro no acesso a LCR" }, ;
      { "297", "Rejeição: Assinatura difere do calculado" }, ;
      { "298", "Rejeição: Assinatura difere do padrão do Sistema" }, ;
      { "299", "Rejeição: XML da área de cabeçalho com codificação diferente de UTF-8" }, ;
      { "301", "Uso Denegado: Irregularidade fiscal do emitente" }, ;
      { "302", "Rejeição: Irregularidade fiscal do destinatário" }, ;
      { "303", "Uso Denegado: Destinatário não habilitado a operar na UF" }, ;
      { "304", "Rejeição: Pedido de Cancelamento para NF-e com evento da Suframa" }, ;
      { "315", "Rejeição: Data de Emissão anterior ao início da autorização de Nota Fiscal na UF" }, ;
      { "316", "Rejeição: Nota Fiscal referenciada com a mesma Chave de Acesso da Nota Fiscal atual" }, ;
      { "317", "Rejeição: NF modelo 1 referenciada com data de emissão inválida" }, ;
      { "318", "Rejeição: Contranota de Produtor sem Nota Fiscal referenciada" }, ;
      { "319", "Rejeição: Contranota de Produtor não pode referenciar somente Nota Fiscal de entrada" }, ;
      { "320", "Rejeição: Contranota de Produtor referencia somente NF de outro emitente" }, ;
      { "321", "Rejeição: NF-e de devolução de mercadoria não possui documento fiscal referenciado" }, ;
      { "322", "Rejeição: NF de produtor referenciada com data de emissão inválida" }, ;
      { "323", "Rejeição: CNPJ autorizado para download inválido" }, ;
      { "324", "Rejeição: CNPJ do destinatário já autorizado para download" }, ;
      { "325", "Rejeição: CPF autorizado para download inválido" }, ;
      { "326", "Rejeição: CPF do destinatário já autorizado para download" }, ;
      { "327", "Rejeição: CFOP inválido para Nota Fiscal com finalidade de devolução de mercadoria [nItem:nnn]" }, ;
      { "328", "Rejeição: CFOP de devolução de mercadoria para NF-e que não tem finalidade de devolução de mercadoria" }, ;
      { "329", "Rejeição: Número da DI /DSI inválido" }, ;
      { "330", "Rejeição: Informar o Valor da AFRMM na importação por via marítima" }, ;
      { "331", "Rejeição: Informar o CNPJ do adquirente ou do encomendante nesta forma de importação" }, ;
      { "332", "Rejeição: CNPJ do adquirente ou do encomendante da importação inválido" }, ;
      { "333", "Rejeição: Informar a UF do adquirente ou do encomendante nesta forma de importação" }, ;
      { "334", "Rejeição: Número do processo de drawback não informado na importação" }, ;
      { "335", "Rejeição: Número do processo de drawback na importação inválido" }, ;
      { "336", "Rejeição: Informado o grupo de exportação no item para CFOP que não é de exportação" }, ;
      { "337", "Rejeição: NFC-e para emitente pessoa física" }, ;
      { "338", "Rejeição: Número do processo de drawback não informado na exportação" }, ;
      { "339", "Rejeição: Número do processo de drawback na exportação inválido" }, ;
      { "340", "Rejeição: Não informado o grupo de exportação indireta no item" }, ;
      { "341", "Rejeição: Número do registro de exportação inválido" }, ;
      { "342", "Rejeição: Chave de Acesso informada na Exportação Indireta com DV inválido" }, ;
      { "343", "Rejeição: Modelo da NF-e informada na Exportação Indireta diferente de 55" }, ;
      { "344", "Rejeição: Duplicidade de NF-e informada na Exportação Indireta (Chave de Acesso informada mais de uma vez)" }, ;
      { "345", "Rejeição: Chave de Acesso informada na Exportação Indireta não consta como NF-e referenciada" }, ;
      { "346", "Rejeição: Somatório das quantidades informadas na Exportação Indiretanão corresponde a quantidade total do item" }, ;
      { "347", "Rejeição: Descrição do combustível diverge da descrição adotada pela ANP" }, ;
      { "348", "Rejeição: NFC-e com grupo RECOPI" }, ;
      { "349", "Rejeição: Número RECOPI não informado" }, ;
      { "350", "Rejeição: Número RECOPI inválido" }, ;
      { "351", "Rejeição: Valor do ICMS da Operação no CST=51 difere do produto BC e Alíquota" }, ;
      { "352", "Rejeição: Valor do ICMS Diferido no CST=51 difere do produto Valor ICMS Operação e percentual diferimento" }, ;
      { "353", "Rejeição: Valor do ICMS no CST=51 não corresponde a diferença do ICMS operação e ICMS diferido" }, ;
      { "354", "Rejeição: Informado grupo de devolução de tributos para NF-e que não tem finalidade de devolução de mercadoria" }, ;
      { "355", "Rejeição: Informar o local de saída do Pais no caso da exportação" }, ;
      { "356", "Rejeição: Informar o local de saída do Pais somente no caso da exportação" }, ;
      { "357", "Rejeição: Chave de Acesso do grupo de Exportação Indireta inexistente [nRef: xxx]" }, ;
      { "358", "Rejeição: Chave de Acesso do grupo de Exportação Indireta cancelada ou denegada [nRef: xxx]" }, ;
      { "359", "Rejeição: NF-e de venda a Órgão Público sem informar a Nota de Empenho" }, ;
      { "360", "Rejeição: NF-e com Nota de Empenho inválida para a UF." }, ;
      { "361", "Rejeição: NF-e com Nota de Empenho inexistente na UF." }, ;
      { "362", "Rejeição: Venda de combustível sem informação do Transportador" }, ;
      { "364", "Rejeição: Total do valor da dedução do ISS difere do somatório dos itens" }, ;
      { "365", "Rejeição: Total de outras retenções difere do somatório dos itens" }, ;
      { "366", "Rejeição: Total do desconto incondicionado ISS difere do somatório dos itens" }, ;
      { "367", "Rejeição: Total do desconto condicionado ISS difere do somatório dos itens" }, ;
      { "368", "Rejeição: Total de ISS retido difere do somatório dos itens" }, ;
      { "369", "Rejeição: Não informado o grupo avulsa na emissão pelo Fisco" }, ;
      { "370", "Rejeição: Nota Fiscal Avulsa com tipo de emissão inválido" }, ;
      { "372", "Rejeição: Destinatário com identificação de estrangeiro com caracteres inválidos" }, ;
      { "373", "Rejeição: Descrição do primeiro item diferente de NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO – SEM VALOR FISCAL" }, ;
      { "374", "Rejeição: CFOP incompatível com o grupo de tributação [nItem:nnn]" }, ;
      { "375", "Rejeição: NF-e com CFOP 5929 (Lançamento relativo a Cupom Fiscal) referencia uma NFC-e [nItem:nnn]" }, ;
      { "376", "Rejeição: Data do Desembaraço Aduaneiro inválida [nItem:nnn]" }, ;
      { "378", "Rejeição: Grupo de Combustível sem a informação de Encerrante [nItem:nnn]" }, ;
      { "379", "Rejeição: Grupo de Encerrante na NF-e (modelo 55) para CFOP diferente de venda de combustível para consumidor final [nItem:nnn]" }, ;
      { "380", "Rejeição: Valor do Encerrante final não é superior ao Encerrante inicial [nItem:nnn]" }, ;
      { "381", "Rejeição:Grupo de tributação ICMS90, informando dados do ICMS-ST [nItem:nnn]" }, ;
      { "382", "Rejeição:CFOP não permitido para o CST informado [nItem:nnn]" }, ;
      { "383", "Rejeição: Item com CSOSN indevido [nItem:nnn]" }, ;
      { "384", "Rejeição: CSOSN não permitido para a UF [nItem:nnn]" }, ;
      { "385", "Rejeição:Grupo de tributação ICMS900, informando dados do ICMS-ST [nItem:nnn]" }, ;
      { "386", "Rejeição: CFOP não permitido para o CSOSN informado [nItem:nnn]" }, ;
      { "387", "Rejeição: Código de Enquadramento Legal do IPI inválido [nItem:nnn]" }, ;
      { "388", "Rejeição: Código de Situação Tributária do IPI incompatível com o Código de Enquadramento Legal do IPI [nItem:nnn]" }, ;
      { "389", "Rejeição: Código Município ISSQN inexistente [nItem:nnn]" }, ;
      { "390", "Rejeição: Nota Fiscal com grupo de devolução de tributos [nItem:nnn]" }, ;
      { "391", "Rejeição: Não informados os dados do cartão de crédito / débito nas Formas de Pagamento da Nota Fiscal" }, ;
      { "392", "Rejeição: Não informados os dados da operação de pagamento por cartão de crédito / débito" }, ;
      { "393", "Rejeição: NF-e com o grupo de Informações Suplementares" }, ;
      { "394", "Rejeição: Nota Fiscal sem a informação do QR-Code" }, ;
      { "395", "Rejeição: Endereço do site da UF da Consulta via QRCode diverge do previsto" }, ;
      { "396", "Rejeição: Parâmetro do QR-Code inexistente (chAcesso)" }, ;
      { "397", "Rejeição: Parâmetro do QR-Code divergente da Nota Fiscal (chAcesso)" }, ;
      { "398", "Rejeição: Parâmetro nVersao do QR-Code difere do previsto" }, ;
      { "399", "Rejeição: Parâmetro de Identificação do destinatário no QR-Code para Nota Fiscal sem identificação do destinatário" }, ;
      { "400", "Rejeição: Parâmetro do QR-Code não está no formato hexadecimal (dhEmi)" }, ;
      { "401", "Rejeição: CPF do emitente inválido" }, ;
      { "402", "Rejeição: XML da área de dados com codificação diferente de UTF-8" }, ;
      { "403", "Rejeição: O grupo de informações da NF-e avulsa é de uso exclusivo do Fisco" }, ;
      { "404", "Rejeição: Uso de prefixo de namespace não permitido" }, ;
      { "405", "Rejeição: Código do país do emitente: dígito inválido" }, ;
      { "406", "Rejeição: Código do país do destinatário: dígito inválido" }, ;
      { "407", "Rejeição: O CPF só pode ser informado no campo emitente para a NF-e avulsa" }, ;
      { "408", "Rejeição: Evento não disponível para Autor pessoa física" }, ;
      { "409", "Rejeição: Campo cUF inexistente no elemento nfeCabecMsg do SOAP Header" }, ;
      { "410", "Rejeição: UF informada no campo cUF não é atendida pelo Web Service" }, ;
      { "411", "Rejeição: Campo versaoDados inexistente no elemento nfeCabecMsg do SOAP Header" }, ;
      { "417", "Rejeição: Total do ICMS superior ao valor limite estabelecido" }, ;
      { "418", "Rejeição: Total do ICMS ST superior ao valor limite estabelecido" }, ;
      { "420", "Rejeição: Cancelamento para NF-e já cancelada" }, ;
      { "450", "Rejeição: Modelo da NF-e diferente de 55" }, ;
      { "451", "Rejeição: Processo de emissão informado inválido" }, ;
      { "452", "Rejeição: Tipo Autorizador do Recibo diverge do Órgão Autorizador" }, ;
      { "453", "Rejeição: Ano de inutilização não pode ser superior ao Ano atual" }, ;
      { "454", "Rejeição: Ano de inutilização não pode ser inferior a 2006" }, ;
      { "455", "Rejeição: Órgão Autor do evento diferente da UF da Chave de Acesso" }, ;
      { "461", "Rejeição: Informado percentual de Gás Natural na mistura para produto diferente de GLP" }, ;
      { "462", "Rejeição:Código Identificador do CSC no QR-Code não cadastrado na SEFAZ" }, ;
      { "463", "Rejeição:Código Identificador do CSC no QR-Code foi revogado pela empresa" }, ;
      { "464", "Rejeição: Código de Hash no QR-Code difere do calculado" }, ;
      { "465", "Rejeição: Número de Controle da FCI inexistente" }, ;
      { "466", "Rejeição: Evento com Tipo de Autor incompatível" }, ;
      { "467", "Rejeição: Dados da NF-e divergentes do EPEC" }, ;
      { "468", "Rejeição: NF-e com Tipo Emissão = 4, sem EPEC correspondente" }, ;
      { "471", "Rejeição: Informado NCM=00 indevidamente" }, ;
      { "476", "Rejeição: Código da UF diverge da UF da primeira NF-e do Lote" }, ;
      { "477", "Rejeição: Código do órgão diverge do órgão do primeiro evento do Lote" }, ;
      { "478", "Rejeição: Local da entrega não informado para faturamento direto de veículos novos" }, ;
      { "479", "Rejeição: Data de Emissão anterior a data de credenciamento ou anterior a Data de Abertura do estabelecimento" }, ;
      { "480", "Rejeição: Código Município do Emitente diverge do cadastrado na UF" }, ;
      { "481", "Rejeição: Código Regime Tributário do emitente diverge do cadastro na SEFAZ" }, ;
      { "482", "Rejeição: Código do Município do Destinatário diverge do cadastrado na UF" }, ;
      { "483", "Rejeição: Valor do desconto maior que valor do produto [nItem:nnn]" }, ;
      { "484", "Rejeição: Chave de Acesso com tipo de emissão diferente de 4 (posição 35 da Chave de Acesso)" }, ;
      { "485", "Rejeição: Duplicidade de numeração do EPEC (Modelo, CNPJ, Série e Número)" }, ;
      { "486", "Rejeição: Não informado o Grupo de Autorização para UF que exige a identificação" }, ;
      { "487", "Rejeição: Escritório de Contabilidade não cadastrado na SEFAZ" }, ;
      { "488", "Rejeição: Vendas do Emitente incompatíveis com o Porte da Empresa" }, ;
      { "489", "Rejeição: CNPJ informado inválido (DV ou zeros)" }, ;
      { "490", "Rejeição: CPF informado inválido (DV ou zeros)" }, ;
      { "491", "Rejeição: O tpEvento informado inválido" }, ;
      { "492", "Rejeição: O verEvento informado inválido" }, ;
      { "493", "Rejeição: Evento não atende o Schema XML específico" }, ;
      { "494", "Rejeição: Chave de Acesso inexistente" }, ;
      { "496", "Rejeição: Não informado o tipo de integração no pagamento com cartão de crédito / débito" }, ;
      { "501", "Rejeição: Pedido de Cancelamento intempestivo (NF-e autorizada a mais de 7 dias)" }, ;
      { "502", "Rejeição: Erro na Chave de Acesso – Campo Id não corresponde à concatenação dos campos correspondentes" }, ;
      { "503", "Rejeição: Série utilizada fora da faixa permitida no SCAN (900-999)" }, ;
      { "504", "Rejeição: Data de Entrada/Saída posterior ao permitido" }, ;
      { "505", "Rejeição: Data de Entrada/Saída anterior ao permitido" }, ;
      { "506", "Rejeição: Data de Saída menor que a Data de Emissão" }, ;
      { "507", "Rejeição: O CNPJ do destinatário/remetente não deve ser informado em operação com o exterior" }, ;
      { "508", "Rejeição: CST incompatível na operação com Não Contribuinte [nItem:999]" }, ;
      { "509", "Rejeição: Informado código de município diferente de “9999999” para operação com o exterior" }, ;
      { "510", "Rejeição: Operação com Exterior e Código País destinatário é 1058 (Brasil) ou não informado" }, ;
      { "511", "Rejeição: Não é de Operação com Exterior e Código País destinatário difere de 1058 (Brasil)" }, ;
      { "512", "Rejeição: CNPJ do Local de Retirada inválido" }, ;
      { "513", "Rejeição: Código Município do Local de Retirada deve ser 9999999 para UF retirada = EX" }, ;
      { "514", "Rejeição: CNPJ do Local de Entrega inválido" }, ;
      { "515", "Rejeição: Código Município do Local de Entrega deve ser 9999999 para UF entrega = EX" }, ;
      { "516", "Rejeição: Falha no schema XML – inexiste a tag raiz esperada para a mensagem" }, ;
      { "517", "Rejeição: Falha no schema XML – inexiste atributo versao na tag raiz da mensagem" }, ;
      { "518", "Rejeição: CFOP de entrada para NF-e de saída" }, ;
      { "519", "Rejeição: CFOP de saída para NF-e de entrada" }, ;
      { "520", "Rejeição: CFOP de Operação com Exterior e UF destinatário difere de EX" }, ;
      { "521", "Rejeição: CFOP de Operação Estadual e UF do emitente difere da UF do destinatário para destinatário contribuinte do ICMS." }, ;
      { "522", "Rejeição: CFOP de Operação Estadual e UF emitente difere da UF remetente para remetente contribuinte do ICMS." }, ;
      { "523", "Rejeição: CFOP não é de Operação Estadual e UF emitente igual a UF destinatário." }, ;
      { "524", "Rejeição: CFOP de Operação com Exterior e não informado NCM" }, ;
      { "525", "Rejeição: CFOP de Importação e não informado dados da DI" }, ;
      { "526", "Rejeição: Consulta a uma Chave de Acesso muito antiga" }, ;
      { "527", "Rejeição: Operação de Exportação com informação de ICMS incompatível" }, ;
      { "528", "Rejeição: Valor do ICMS difere do produto BC e Alíquota" }, ;
      { "529", "Rejeição: CST incompatível na operação com Contribuinte Isento de Inscrição Estadual [nItem:999]" }, ;
      { "530", "Rejeição: Operação com tributação de ISSQN sem informar a Inscrição Municipal" }, ;
      { "531", "Rejeição: Total da BC ICMS difere do somatório dos itens" }, ;
      { "532", "Rejeição: Total do ICMS difere do somatório dos itens" }, ;
      { "533", "Rejeição: Total da BC ICMS-ST difere do somatório dos itens" }, ;
      { "534", "Rejeição: Total do ICMS-ST difere do somatório dos itens" }, ;
      { "535", "Rejeição: Total do Frete difere do somatório dos itens" }, ;
      { "536", "Rejeição: Total do Seguro difere do somatório dos itens" }, ;
      { "537", "Rejeição: Total do Desconto difere do somatório dos itens" }, ;
      { "538", "Rejeição: Total do IPI difere do somatório dos itens" }, ;
      { "539", "Duplicidade de NF-e com diferença na Chave de Acesso [chNFe: 99999999999999999999999999999999999999999999][nRec:999999999999999]" }, ;
      { "540", "Rejeição: CPF do Local de Retirada inválido" }, ;
      { "541", "Rejeição: CPF do Local de Entrega inválido" }, ;
      { "542", "Rejeição: CNPJ do Transportador inválido" }, ;
      { "543", "Rejeição: CPF do Transportador inválido" }, ;
      { "544", "Rejeição: IE do Transportador inválida" }, ;
      { "545", "Rejeição: Falha no schema XML – versão informada na versaoDados do SOAPHeader diverge da versão da mensagem" }, ;
      { "546", "Rejeição: Erro na Chave de Acesso – Campo Id – falta a literal NFe" }, ;
      { "547", "Rejeição: Dígito Verificador da Chave de Acesso da NF-e Referenciada inválido" }, ;
      { "548", "Rejeição: CNPJ da NF referenciada inválido." }, ;
      { "549", "Rejeição: CNPJ da NF referenciada de produtor inválido." }, ;
      { "550", "Rejeição: CPF da NF referenciada de produtor inválido." }, ;
      { "551", "Rejeição: IE da NF referenciada de produtor inválido." }, ;
      { "552", "Rejeição: Dígito Verificador da Chave de Acesso do CT-e Referenciado inválido" }, ;
      { "553", "Rejeição: Tipo autorizador do recibo diverge do Órgão Autorizador." }, ;
      { "554", "Rejeição: Série difere da faixa 0-899" }, ;
      { "555", "Rejeição: Tipo autorizador do protocolo diverge do Órgão Autorizador." }, ;
      { "556", "Rejeição: Justificativa de entrada em contingência não deve ser informada para tipo de emissão normal." }, ;
      { "557", "Rejeição: A Justificativa de entrada em contingência deve ser informada." }, ;
      { "558", "Rejeição: Data de entrada em contingência posterior a data de recebimento." }, ;
      { "559", "Rejeição: UF do Transportador não informada" }, ;
      { "560", "Rejeição: CNPJ base do emitente difere do CNPJ base da primeira NF-e do lote recebido" }, ;
      { "561", "Rejeição: Mês de Emissão informado na Chave de Acesso difere do Mês de Emissão da NF-e" }, ;
      { "562", "Rejeição: Código Numérico informado na Chave de Acesso difere do Código Numérico da NF-e [chNFe:99999999999999999999999999999999999999999999]" }, ;
      { "563", "Rejeição: Já existe pedido de Inutilização com a mesma faixa de inutilização" }, ;
      { "564", "Rejeição: Total do Produto / Serviço difere do somatório dos itens" }, ;
      { "565", "Rejeição: Falha no schema XML – inexiste a tag raiz esperada para o lote de NF-e" }, ;
      { "567", "Rejeição: Falha no schema XML – versão informada na versaoDados do SOAPHeader diverge da versão do lote de NF-e" }, ;
      { "568", "Rejeição: Falha no schema XML – inexiste atributo versao na tag raiz do lote de NF-e" }, ;
      { "569", "Rejeição: Data de entrada em contingência muito atrasada" }, ;
      { "570", "Rejeição: Tipo de Emissão 3, 6 ou 7 só é válido nas contingências SCAN/SVC" }, ;
      { "571", "Rejeição: O tpEmis informado diferente de 3 para contingência SCAN" }, ;
      { "572", "Rejeição: Erro Atributo ID do evento não corresponde a concatenação dos campos (“ID” + tpEvento + chNFe + nSeqEvento)" }, ;
      { "573", "Rejeição: Duplicidade de Evento" }, ;
      { "574", "Rejeição: O autor do evento diverge do emissor da NF-e" }, ;
      { "575", "Rejeição: O autor do evento diverge do destinatário da NF-e" }, ;
      { "576", "Rejeição: O autor do evento não é um órgão autorizado a gerar o evento" }, ;
      { "577", "Rejeição: A data do evento não pode ser menor que a data de emissão da NF-e" }, ;
      { "578", "Rejeição: A data do evento não pode ser maior que a data do processamento" }, ;
      { "579", "Rejeição: A data do evento não pode ser menor que a data de autorização para NF-e não emitida em contingência" }, ;
      { "580", "Rejeição: O evento exige uma NF-e autorizada" }, ;
      { "587", "Rejeição: Usar somente o namespace padrão da NF-e" }, ;
      { "588", "Rejeição: Não é permitida a presença de caracteres de edição no início/fim da mensagem ou entre as tags da mensagem" }, ;
      { "589", "Rejeição: Número do NSU informado superior ao maior NSU da base de dados da SEFAZ" }, ;
      { "590", "Rejeição: Informado CST para emissor do Simples Nacional (CRT=1)" }, ;
      { "591", "Rejeição: Informado CSOSN para emissor que não é do Simples Nacional (CRT diferente de 1)" }, ;
      { "592", "Rejeição: A NF-e deve ter pelo menos um item de produto sujeito ao ICMS" }, ;
      { "593", "Rejeição: CNPJ-Base consultado difere do CNPJ-Base do Certificado Digital" }, ;
      { "594", "Rejeição: O número de sequencia do evento informado é maior que o permitido" }, ;
      { "595", "Rejeição: Obrigatória a informação da justificativa do evento." }, ;
      { "596", "Rejeição: Evento apresentado fora do prazo: [prazo vigente]" }, ;
      { "597", "Rejeição: CFOP de Importação e não informado dados de IPI" }, ;
      { "598", "Rejeição: NF-e emitida em ambiente de homologação com Razão Social do destinatário diferente de NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO – SEM VALOR FISCAL" }, ;
      { "599", "Rejeição: CFOP de Importação e não informado dados de II" }, ;
      { "600", "Rejeição: CSOSN incompatível na operação com Não Contribuinte [nItem:999]" }, ;
      { "601", "Rejeição: Total do II difere do somatório dos itens" }, ;
      { "602", "Rejeição: Total do PIS difere do somatório dos itens sujeitos ao ICMS" }, ;
      { "603", "Rejeição: Total do COFINS difere do somatório dos itens sujeitos ao ICMS" }, ;
      { "604", "Rejeição: Total do vOutro difere do somatório dos itens" }, ;
      { "605", "Rejeição: Total do vISS difere do somatório do vProd dos itens sujeitos ao ISSQN" }, ;
      { "606", "Rejeição: Total do vBC do ISS difere do somatório dos itens" }, ;
      { "607", "Rejeição: Total do ISS difere do somatório dos itens" }, ;
      { "608", "Rejeição: Total do PIS difere do somatório dos itens sujeitos ao ISSQN" }, ;
      { "609", "Rejeição: Total do COFINS difere do somatório dos itens sujeitos ao ISSQN" }, ;
      { "610", "Rejeição: Total da NF difere do somatório dos Valores compõe o valor Total da NF." }, ;
      { "611", "Rejeição: cEAN inválido" }, ;
      { "612", "Rejeição: cEANTrib inválido" }, ;
      { "613", "Rejeição: Chave de Acesso difere da existente em BD" }, ;
      { "614", "Rejeição: Chave de Acesso inválida (Código UF inválido)" }, ;
      { "615", "Rejeição: Chave de Acesso inválida (Ano menor que 06 ou Ano maior que Ano corrente)" }, ;
      { "616", "Rejeição: Chave de Acesso inválida (Mês menor que 1 ou Mês maior que 12)" }, ;
      { "617", "Rejeição: Chave de Acesso inválida (CNPJ zerado ou dígito inválido)" }, ;
      { "618", "Rejeição: Chave de Acesso inválida (modelo diferente de 55 e 65)" }, ;
      { "619", "Rejeição: Chave de Acesso inválida (número NF = 0)" }, ;
      { "620", "Rejeição: Chave de Acesso difere da existente em BD" }, ;
      { "621", "Rejeição: CPF Emitente não cadastrado" }, ;
      { "622", "Rejeição: IE emitente não vinculada ao CPF" }, ;
      { "623", "Rejeição: CPF Destinatário não cadastrado" }, ;
      { "624", "Rejeição: IE Destinatário não vinculada ao CPF" }, ;
      { "625", "Rejeição: Inscrição SUFRAMA deve ser informada na venda com isenção para ZFM" }, ;
      { "626", "Rejeição: CFOP de operação isenta para ZFM diferente do previsto" }, ;
      { "627", "Rejeição: O valor do ICMS desonerado deve ser informado" }, ;
      { "628", "Rejeição: Total da NF superior ao valor limite estabelecido pela SEFAZ [Limite]" }, ;
      { "629", "Rejeição: Valor do Produto difere do produto Valor Unitário de Comercialização e Quantidade Comercial" }, ;
      { "630", "Rejeição: Valor do Produto difere do produto Valor Unitário de Tributação e Quantidade Tributável" }, ;
      { "631", "Rejeição: CNPJ-Base do Destinatário difere do CNPJ-Base do Certificado Digital" }, ;
      { "632", "Rejeição: Solicitação fora de prazo, a NF-e não está mais disponível para download" }, ;
      { "633", "Rejeição: NF-e indisponível para download devido a ausência de Manifestação do Destinatário" }, ;
      { "634", "Rejeição: Destinatário da NF-e não tem o mesmo CNPJ raiz do solicitante do download" }, ;
      { "635", "Rejeição: NF-e com mesmo número e série já transmitida e aguardando processamento" }, ;
      { "650", "Rejeição: Evento de “Ciência da Emissão” para NF-e Cancelada ou Denegada" }, ;
      { "651", "Rejeição: Evento de “Desconhecimento da Operação” para NF-e Cancelada ou Denegada" }, ;
      { "653", "Rejeição: NF-e Cancelada, arquivo indisponível para download" }, ;
      { "654", "Rejeição: NF-e Denegada, arquivo indisponível para download" }, ;
      { "655", "Rejeição: Evento de Ciência da Emissão informado após a manifestação final do destinatário" }, ;
      { "656", "Rejeição: Consumo Indevido" }, ;
      { "657", "Rejeição: Código do Órgão diverge do órgão autorizador" }, ;
      { "658", "Rejeição: UF do destinatário da Chave de Acesso diverge da UF autorizadora" }, ;
      { "660", "Rejeição: CFOP de Combustível e não informado grupo de combustível [nItem:nnn]" }, ;
      { "661", "Rejeição: NF-e já existente para o número do EPEC informado" }, ;
      { "662", "Rejeição: Numeração do EPEC está inutilizada na Base de Dados da SEFAZ" }, ;
      { "663", "Rejeição: Alíquota do ICMS com valor superior a 4 por cento na operação de saída interestadual com produtos importados [nItem:999]" }, ;
      { "678", "Rejeição: NF referenciada com UF diferente da NF-e complementar" }, ;
      { "679", "Rejeição: Modelo de DF-e referenciado inválido" }, ;
      { "680", "Rejeição: Duplicidade de NF-e referenciada (Chave de Acesso referenciada mais de uma vez)" }, ;
      { "681", "Rejeição: Duplicidade de NF Modelo 1 referenciada (CNPJ, Modelo, Série e Número)" }, ;
      { "682", "Rejeição: Duplicidade de NF de Produtor referenciada (IE, Modelo, Série e Número)" }, ;
      { "683", "Rejeição: Modelo do CT-e referenciado diferente de 57" }, ;
      { "684", "Rejeição: Duplicidade de Cupom Fiscal referenciado (Modelo, Número de Ordem e COO)" }, ;
      { "685", "Rejeição: Total do Valor Aproximado dos Tributos difere do somatório dos itens" }, ;
      { "686", "Rejeição: NF Complementar referencia uma NF-e cancelada" }, ;
      { "687", "Rejeição: NF Complementar referencia uma NF-e denegada" }, ;
      { "688", "Rejeição: NF referenciada de Produtor com IE inexistente [nRef: xxx]" }, ;
      { "689", "Rejeição: NF referenciada de Produtor com IE não vinculada ao CNPJ/CPF informado [nRef: xxx]" }, ;
      { "690", "Rejeição: Pedido de Cancelamento para NF-e com CT-e" }, ;
      { "691", "Rejeição: Chave de Acesso da NF-e diverge da Chave de Acesso do EPEC" }, ;
      { "693", "Rejeição: Alíquota de ICMS superior a definida para a operação interestadual [nItem:999]" }, ;
      { "694", "Rejeição: Não informado o grupo de ICMS para a UF de destino [nItem:999]" }, ;
      { "695", "Rejeição: Informado indevidamente o grupo de ICMS para a UF de destino [nItem:999]" }, ;
      { "697", "Rejeição: Alíquota interestadual do ICMS com origem diferente do previsto [nItem:999]" }, ;
      { "698", "Rejeição: Alíquota interestadual do ICMS incompatível com as UF envolvidas na operação [nItem:999]" }, ;
      { "699", "Rejeição: Percentual do ICMS Interestadual para a UF de destino difere do previsto para o ano da Data de Emissão [nItem:999]" }, ;
      { "700", "Rejeição: Mensagem de Lote versão 3.xx. Enviar para o Web Service nfeAutorizacao" }, ;
      { "701", "Rejeição: Não informado Nota Fiscal referenciada (CFOP de Exportação Indireta)" }, ;
      { "702", "Rejeição: NFC-e não é aceita pela UF do Emitente" }, ;
      { "703", "Rejeição: Data-Hora de Emissão posterior ao horário de recebimento" }, ;
      { "704", "Rejeição: NFC-e com Data-Hora de emissão atrasada" }, ;
      { "705", "Rejeição: NFC-e com data de entrada/saída" }, ;
      { "706", "Rejeição: NFC-e para operação de entrada" }, ;
      { "707", "Rejeição: NFC-e para operação interestadual ou com o exterior" }, ;
      { "708", "Rejeição: NFC-e não pode referenciar documento fiscal" }, ;
      { "709", "Rejeição: NFC-e com formato de DANFE inválido" }, ;
      { "710", "Rejeição: NF-e com formato de DANFE inválido" }, ;
      { "711", "Rejeição: NF-e com contingência off-line" }, ;
      { "712", "Rejeição: NFC-e com contingência off-line para a UF" }, ;
      { "713", "Rejeição: Tipo de Emissão diferente de 6 ou 7 para contingência da SVC acessada" }, ;
      { "714", "Rejeição: NFC-e com opção de contingência inválida (tpEmis=2, 4 (a critério da UF) ou 5)" }, ;
      { "715", "Rejeição: NFC-e com finalidade inválida" }, ;
      { "716", "Rejeição: NFC-e em operação não destinada a consumidor final" }, ;
      { "717", "Rejeição: NFC-e em operação não presencial" }, ;
      { "718", "Rejeição: NFC-e não deve informar IE de Substituto Tributário" }, ;
      { "719", "Rejeição: NF-e sem a identificação do destinatário" }, ;
      { "720", "Rejeição: Na operação com Exterior deve ser informada tag idEstrangeiro" }, ;
      { "721", "Rejeição: Operação interestadual deve informar CNPJ ou CPF" }, ;
      { "723", "Rejeição: Operação interna com idEstrangeiro informado deve ser para consumidor final" }, ;
      { "724", "Rejeição: NF-e sem o nome do destinatário" }, ;
      { "725", "Rejeição: NFC-e com CFOP inválido [nItem:nnn]" }, ;
      { "726", "Rejeição: NF-e sem a informação de endereço do destinatário" }, ;
      { "727", "Rejeição: Operação com Exterior e UF diferente de EX" }, ;
      { "728", "Rejeição: NF-e sem informação da IE do destinatário" }, ;
      { "729", "Rejeição: NFC-e com informação da IE do destinatário" }, ;
      { "730", "Rejeição: NFC-e com Inscrição Suframa" }, ;
      { "731", "Rejeição: CFOP de operação com Exterior e idDest <> 3" }, ;
      { "732", "Rejeição: CFOP de operação interestadual e idDest <> 2" }, ;
      { "733", "Rejeição: CFOP de operação interna e idDest <> 1" }, ;
      { "734", "Rejeição: NFC-e com Unidade de Comercialização inválida" }, ;
      { "735", "Rejeição: NFC-e com Unidade de Tributação inválida" }, ;
      { "736", "Rejeição: NFC-e com grupo de Veículos novos" }, ;
      { "737", "Rejeição: NFC-e com grupo de Medicamentos" }, ;
      { "738", "Rejeição: NFC-e com grupo de Armamentos" }, ;
      { "740", "Rejeição: Item com Repasse de ICMS retido por Substituto Tributário [nItem:nnn]" }, ;
      { "741", "Rejeição: NFC-e com Partilha de ICMS entre UF" }, ;
      { "742", "Rejeição: NFC-e com grupo do IPI" }, ;
      { "743", "Rejeição: NFC-e com grupo do II" }, ;
      { "745", "Rejeição: NF-e sem grupo do PIS" }, ;
      { "746", "Rejeição: NFC-e com grupo do PIS-ST" }, ;
      { "748", "Rejeição: NF-e sem grupo da COFINS" }, ;
      { "749", "Rejeição: NFC-e com grupo da COFINS-ST" }, ;
      { "750", "Rejeição: NFC-e com valor total superior ao permitido para destinatário não identificado (Código) [Limite]" }, ;
      { "751", "Rejeição: NFC-e com valor total superior ao permitido para destinatário não identificado (Nome) [Limite]" }, ;
      { "752", "Rejeição: NFC-e com valor total superior ao permitido para destinatário não identificado (Endereço) [Limite]" }, ;
      { "753", "Rejeição: NFC-e com Frete" }, ;
      { "754", "Rejeição: NFC-e com dados do Transportador" }, ;
      { "755", "Rejeição: NFC-e com dados de Retenção do ICMS no Transporte" }, ;
      { "756", "Rejeição: NFC-e com dados do veículo de Transporte" }, ;
      { "757", "Rejeição: NFC-e com dados de Reboque do veículo de Transporte" }, ;
      { "758", "Rejeição: NFC-e com dados do Vagão de Transporte" }, ;
      { "759", "Rejeição: NFC-e com dados da Balsa de Transporte" }, ;
      { "760", "Rejeição: NFC-e com dados de cobrança (Fatura, Duplicata)" }, ;
      { "761", "Rejeição: Código de Produtos ANP inexistente" }, ;
      { "762", "Rejeição: NFC-e com dados de compras (Empenho, Pedido, Contrato)" }, ;
      { "763", "Rejeição: NFC-e com dados de aquisição de Cana" }, ;
      { "764", "Rejeição: Solicitada resposta síncrona para Lote com mais de uma NF-e (indSinc=1)" }, ;
      { "765", "Rejeição: Lote só poderá conter NF-e ou NFC-e" }, ;
      { "766", "Rejeição: Item com CST indevido [nItem:nnn]" }, ;
      { "767", "Rejeição: NFC-e com somatório dos pagamentos diferente do total da Nota Fiscal" }, ;
      { "768", "Rejeição: NF-e não deve possuir o grupo de Formas de Pagamento" }, ;
      { "769", "Rejeição: A critério da UF NFC-e deve possuir o grupo de Formas de Pagamento" }, ;
      { "770", "Rejeição: NFC-e autorizada há mais de 24 horas." }, ;
      { "771", "Rejeição: Operação Interestadual e UF de destino com EX" }, ;
      { "772", "Rejeição: Operação Interestadual e UF de destino igual à UF do emitente" }, ;
      { "773", "Rejeição: Operação Interna e UF de destino difere da UF do emitente" }, ;
      { "774", "Rejeição: NFC-e com indicador de item não participante do total" }, ;
      { "775", "Rejeição: Modelo da NFC-e diferente de 65" }, ;
      { "776", "Rejeição: Solicitada resposta síncrona para UF que não disponibiliza este atendimento (indSinc=1)" }, ;
      { "777", "Rejeição: Obrigatória a informação do NCM completo" }, ;
      { "778", "Rejeição: Informado NCM inexistente [nItem:nnn]" }, ;
      { "779", "Rejeição: NFC-e com NCM incompatível" }, ;
      { "780", "Rejeição: Total da NFC-e superior ao valor limite estabelecido pela SEFAZ [Limite]" }, ;
      { "781", "Rejeição: Emissor não habilitado para emissão da NFC-e" }, ;
      { "782", "Rejeição: NFC-e não é autorizada pelo SCAN" }, ;
      { "783", "Rejeição: NFC-e não é autorizada pela SVC" }, ;
      { "784", "Rejeição: NFC-e não permite o evento de Carta de Correção" }, ;
      { "785", "Rejeição: NFC-e com entrega a domicílio não permitida pela UF" }, ;
      { "786", "Rejeição: NFC-e de entrega a domicílio sem dados do Transportador" }, ;
      { "787", "Rejeição: NFC-e de entrega a domicílio sem a identificação do destinatário" }, ;
      { "788", "Rejeição: NFC-e de entrega a domicílio sem o endereço do destinatário" }, ;
      { "789", "Rejeição: NFC-e para destinatário contribuinte de ICMS" }, ;
      { "790", "Rejeição: Operação com Exterior para destinatário Contribuinte de ICMS" }, ;
      { "791", "Rejeição: NF-e com indicação de destinatário isento de IE, com a informação da IE do destinatário" }, ;
      { "792", "Rejeição: Informada a IE do destinatário para operação com destinatário no Exterior" }, ;
      { "793", "Rejeição: Valor do ICMS relativo ao Fundo de Combate à Pobreza na UF de destino difere do calculado [nItem:999]" }, ;
      { "794", "Rejeição: NF-e com indicativo de NFC-e com entrega a domicílio" }, ;
      { "795", "Rejeição: Total do ICMS desonerado difere do somatório dos itens" }, ;
      { "796", "Rejeição: Empresa sem Chave de Segurança para o QR-Code" }, ;
      { "798", "Rejeição: Valor total do ICMS relativo Fundo de Combate à Pobreza (FCP) da UF de destino difere do somatório do valor dos itens" }, ;
      { "799", "Rejeição: Valor total do ICMS Interestadual da UF de destino difere do somatório dos itens" }, ;
      { "800", "Rejeição: Valor total do ICMS Interestadual da UF do remetente difere do somatório dos itens" }, ;
      { "805", "Rejeição: A SEFAZ do destinatário não permite Contribuinte Isento de Inscrição Estadual" }, ;
      { "806", "Rejeição: Operação com ICMS-ST sem informação do CEST" }, ;
      { "807", "Rejeição: NFC-e com grupo de ICMS para a UF do destinatário" }, ;
      { "999", "Rejeição: Erro não catalogado (informar a mensagem de erro capturado no tratamento da exceção)" } }
*/
