#
# mingw_.yml
#
# input:  mingw_0703.zip
# input:  mingw_1420.zip
# input:  mingw_1500.zip
# output: mingw_0703.zip
# output: mingw_1420.zip
# output: mingw_xxxx.zip
#

name: mingw

on:
#  push:
  schedule:
   - cron: "0 3 1 * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'mingw'
        default: 'mingw'
        required: true

jobs:

  mingw0703:
    runs-on: windows-latest
    strategy:
       matrix:
          compiler:
          - mingw_0703
          - mingw_1420
          - mingw_1500
    steps:

    - name: load mingw_xxxx.zip from workflow
      uses: dawidd6/action-download-artifact@v6
      with:
         workflow: mingw.yml
         workflow_conclusion: success
         name: ${{matrix.compiler}}
         path: c:\temp
         repo: JoseQuintas/sefazclass

    - name: Save mingw_xxxx.zip to workflow
      uses: actions/upload-artifact@v4
      with:
         name: ${{matrix.compiler}}
         path: c:\temp\${{matrix.compiler}}.7z
